#!/bin/zsh
#
# .zimrc - Zim configuration file.
#

# ---------- Base Zim modules ----------
zmodule completion
zmodule environment

# ---------- Base Zim plugins ----------
zmodule archive
zmodule fzf
zmodule termtitle
zmodule utility

# ---------- Completions plugins ----------
zmodule zsh-users/zsh-completions --fpath src
zmodule gradle/gradle-completion --fpath .

# ---------- Prompt theme ----------
zmodule romkatv/powerlevel10k

# ---------- Aliases ----------
zmodule ohmyzsh/ohmyzsh --root plugins/eza
zmodule ohmyzsh/ohmyzsh --root plugins/git
zmodule ohmyzsh/ohmyzsh --root plugins/archlinux

# ---------- Otros plugins ----------
zmodule ajeetdsouza/zoxide
zmodule Aloxaf/fzf-tab
zmodule ohmyzsh/ohmyzsh --root plugins/ssh-agent
zmodule ohmyzsh/ohmyzsh --root plugins/command-not-found
zmodule ohmyzsh/ohmyzsh --root plugins/aliases
zmodule ohmyzsh/ohmyzsh --root plugins/alias-finder

# ---------- Plugins fish style ----------
zmodule zsh-users/zsh-autosuggestions
zmodule zdharma-continuum/fast-syntax-highlighting
zmodule zsh-users/zsh-history-substring-search
# zmodule marlonrichert/zsh-autocomplete
